# Generated by Django 5.0.1 on 2024-03-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("link", models.URLField()),
                ("platform", models.CharField(default="amazon", max_length=50)),
                ("about", models.TextField()),
                ("description", models.TextField()),
            ],
        ),
    ]
