# Generated by Django 5.0.1 on 2024-03-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_timestamp_product_updated_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="short_link",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
    ]
