# Generated by Django 5.0.1 on 2024-03-11 23:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_productrequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
        migrations.RemoveField(
            model_name="product",
            name="short_link",
        ),
    ]
