# Generated by Django 5.0.1 on 2024-03-12 23:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_remove_product_description_remove_product_short_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productrequest",
            name="link",
            field=models.URLField(max_length=500),
        ),
    ]
