# Generated by Django 5.0.1 on 2024-03-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_product_image_alter_productrequest_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.URLField(default="https://google.com"),
            preserve_default=False,
        ),
    ]
