# Generated by Django 5.0.1 on 2024-03-15 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="link",
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="productrequest",
            name="link",
            field=models.URLField(max_length=1000),
        ),
    ]
